# Application paths
paths:
  logs: logs
  meetings: meetings
  screenshots: screenshots

# Azure configuration (can be overridden by environment variables)
azure:
  speech_key: '' # Set via AZURE_SPEECH_KEY env var
  speech_region: '' # Set via AZURE_SPEECH_REGION env var

# Transcription settings
transcription:
  output_format: 'md' # md or txt
  language: 'en-US'
  enable_timestamps: true

# Logging settings
logging:
  level: 'DEBUG' # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_logging_enabled: false

# User settings
user:
  default_participant: 'Konrad Heimel'
  create_default_meeting: true

# Audio capture settings
audio:
  enabled: true # Disabled by default
  format: 32 # paFloat32
  channels: 1
  rate: 16000
  chunk: 1024
