# Application paths
paths:
  logs: logs
  meetings: meetings
  screenshots: screenshots

# Azure configuration (can be overridden by environment variables)
azure:
  speech_key: ""  # Set via AZURE_SPEECH_KEY env var
  speech_region: ""  # Set via AZURE_SPEECH_REGION env var

# Transcription settings
transcription:
  output_format: "md"  # md or txt
  language: "en-US"
  enable_timestamps: true
